services:
  postgres:
    image: postgres:15
    container_name: postgres_db
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      retries: 5
      start_period: 10s
      timeout: 5s

  pipeline:
    build: .
    container_name: data_pipeline
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - .env
    environment:
      CONFIG_PATH: /app/config/config.yaml
      LOG_DIR: /app/logs
    volumes:
      - ./config:/app/config
      - ./data:/app/data
      - ./logs:/app/logs
    command: ["python", "src/pipeline.py"]